exclude:
  - node_modules
  - script
  - Gemfile
  - Gemfile.lock

repository: https://github.com/learngift/learngift.github.com

author: e70838

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

tag_permalink_style: pretty

markdown: kramdown
kramdown:
  input: Kramdown
  syntax_highlighter: rouge

title: LearnGift
description: Ressources pédagogiques sur Maven, Python, Linux et les Mathématiques

